version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - ENV=development
    volumes:
      - ./backend:/app
      - /app/tmp
    depends_on:
      - postgres
    networks:
      - platform-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - platform-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=platform_db
      - POSTGRES_USER=platform_user
      - POSTGRES_PASSWORD=platform_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - platform-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - platform-network

volumes:
  postgres_data:

networks:
  platform-network:
    driver: bridge
