version: '3.8'

services:
  platform:
    image: my-platform:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=platform
      - DB_USER=platform
      - DB_PASS=${DB_PASSWORD:-changeme}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - platform-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=platform
      - POSTGRES_USER=platform
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U platform"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - platform-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - platform-network

volumes:
  postgres_data:
    driver: local

networks:
  platform-network:
    driver: bridge
